output_folder: pandora_output_pandora_paper_tag1_4way_old_basecall

coverages:
  - 100

subsamplings:
  - random

technologies:
  - nanopore

samples: metadata/samples_pandora_paper_tag1.4way_old_basecall.csv
subsampled_reads_dir: metadata/subsampled_reads_pandora_paper_tag1.4way_old_basecall.csv
msas_dir: ../data/msas

pandora_URL: "https://github.com/rmcolq/pandora/releases/download/0.9.1/pandora-linux-precompiled-v0.9.1"
containers:
  make_prg: docker://leandroishilima/make_prg:1.0.0
