output_folder: pandora_output_pandora_paper_tag1

coverages:
  - 100

subsamplings:
  - random

technologies:
  - illumina
  - nanopore

samples: metadata/samples_pandora_paper_tag1.csv
subsampled_reads_dir: metadata/subsampled_reads_pandora_paper_tag1.csv
msas_dir: ../data/msas

pandora_URL: "https://www.dropbox.com/s/r5osl8sqno7o8q1/pandora-linux-precompiled-glibc-v2?dl=1"
containers:
  make_prg: docker://leandroishilima/make_prg:1.0.0
