output_folder: pandora_output_pandora_paper_tag1_4way_old_basecall

coverages:
  - 100

subsamplings:
  - random

technologies:
  - nanopore

samples: metadata/samples_pandora_paper_tag1.4way_old_basecall.csv
subsampled_reads_dir: metadata/subsampled_reads_pandora_paper_tag1.4way_old_basecall.csv
msas_dir: ../data/msas

pandora_URL: "https://www.dropbox.com/s/psqb303s0osemxh/pandora_b19d26_release?dl=1"
containers:
  make_prg: docker://quay.io/biocontainers/make_prg:0.4.0--pyhdfd78af_0
